export { Header } from './Header'
export { Footer } from './Footer'
export { FetchTopMovie } from './TopFilms'
export { FetchRandomMovie } from './Promo'
export { FetchGenreMovie } from './Genres'
export { FetchSortedMovie } from './Genre'
export { HeaderAccount } from './Header'
export { Layout } from "./Layout";
export { Trailer } from './Trailer'