export { SvgEmail } from './svgEmail'
export { SvgName } from './svgName'
export { SvgPass } from './svgPass'
export { SvgGenres } from './svgGenres'
export { SvgSearch } from './svgSearch'
export { SvgUser } from './svgUser'
export { SvgUserLogined } from './svgUserLogined'
